In [1]:
import pandas as pd

In [2]:
titanic_train = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")   
titanic_train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [4]:
dy = titanic_train.dtypes

In [5]:
dy['Pclass']

dtype('int64')

In [7]:
import numpy as np

In [8]:
nanList = np.where(titanic_train['Age'].isnull() == True)

In [9]:
nanList

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
        196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
        270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
        334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
        409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
        459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
        511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
        564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
        613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
        692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
        773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
        839, 846, 849, 859, 863, 868, 878, 888], dt

In [10]:
titanic_train.iloc[nanList]

PassengerId  Survived  Pclass                                      Name  \
5              6         0       3                          Moran, Mr. James   
17            18         1       2              Williams, Mr. Charles Eugene   
19            20         1       3                   Masselmani, Mrs. Fatima   
26            27         0       3                   Emir, Mr. Farred Chehab   
28            29         1       3             O'Dwyer, Miss. Ellen "Nellie"   
..           ...       ...     ...                                       ...   
859          860         0       3                          Razi, Mr. Raihed   
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0       3               van Melkebeke, Mr. Philemon   
878          879         0       3                        Laleff, Mr. Kristo   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex  Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
5      male  NaN      0      0      330877   8.4583   NaN        Q  
17     male  NaN      0      0      244373  13.0000   NaN        S  
19   female  NaN      0      0        2649   7.2250   NaN        C  
26     male  NaN      0      0        2631   7.2250   NaN        C  
28   female  NaN      0      0      330959   7.8792   NaN        Q  
..      ...  ...    ...    ...         ...      ...   ...      ...  
859    male  NaN      0      0        2629   7.2292   NaN        C  
863  female  NaN      8      2    CA. 2343  69.5500   NaN        S  
868    male  NaN      0      0      345777   9.5000   NaN        S  
878    male  NaN      0      0      349217   7.8958   NaN        S  
888  female  NaN      1      2  W./C. 6607  23.4500   NaN        S  

[177 rows x 12 columns]

In [11]:
high_fare = np.where(titanic_train['Fare'] == max(titanic_train['Fare']))

In [12]:
high_fare

(array([258, 679, 737], dtype=int64),)

In [16]:
titanic_train.iloc[high_fare][['Name']]

Name
258                    Ward, Miss. Anna
679  Cardeza, Mr. Thomas Drake Martinez
737              Lesurer, Mr. Gustave J

In [17]:
age24 = np.where(titanic_train['Age'] == 24)

In [18]:
age24

(array([ 89, 118, 127, 139, 142, 199, 210, 234, 247, 293, 294, 310, 316,
        341, 345, 369, 394, 437, 499, 514, 565, 600, 615, 641, 655, 710,
        743, 770, 858, 864], dtype=int64),)

In [20]:
titanic_train.iloc[age24][['Name']]

Name
89                              Celotti, Mr. Francesco
118                           Baxter, Mr. Quigg Edmond
127                          Madsen, Mr. Fridtjof Arne
139                                 Giglio, Mr. Victor
142  Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...
199             Yrois, Miss. Henriette ("Mrs Harbeck")
210                                     Ali, Mr. Ahmed
234                  Leyson, Mr. Robert William Norman
247                    Hamalainen, Mrs. William (Anna)
293                                Haas, Miss. Aloisia
294                                   Mineff, Mr. Ivan
310                     Hays, Miss. Margaret Bechstein
316                Kantor, Mrs. Sinai (Miriam Sternin)
341                     Fortune, Miss. Alice Elizabeth
345                      Brown, Miss. Amelia "Mildred"
369                      Aubart, Mme. Leontine Pauline
394  Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengt...
437              Richards, Mrs. Sidney (Emily Hocking)
499                                 Svensson, Mr. Olof
514                                  Coleff, Mr. Satio
565                               Davies, Mr. Alfred J
600  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...
615                                Herman, Miss. Alice
641                               Sagesser, Mlle. Emma
655                          Hickman, Mr. Leonard Mark
710   Mayne, Mlle. Berthe Antonine ("Mrs de Villiers")
743                                  McNamee, Mr. Neal
770                             Lievens, Mr. Rene Aime
858              Baclini, Mrs. Solomon (Latifa Qurban)
864                             Gill, Mr. John William

In [21]:
 cabinNA = np.where(titanic_train['Cabin'].isnull() == True)

In [22]:
cabinNA

(array([  0,   2,   4,   5,   7,   8,   9,  12,  13,  14,  15,  16,  17,
         18,  19,  20,  22,  24,  25,  26,  28,  29,  30,  32,  33,  34,
         35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,
         48,  49,  50,  51,  53,  56,  57,  58,  59,  60,  63,  64,  65,
         67,  68,  69,  70,  71,  72,  73,  74,  76,  77,  78,  79,  80,
         81,  82,  83,  84,  85,  86,  87,  89,  90,  91,  93,  94,  95,
         98,  99, 100, 101, 103, 104, 105, 106, 107, 108, 109, 111, 112,
        113, 114, 115, 116, 117, 119, 120, 121, 122, 125, 126, 127, 129,
        130, 131, 132, 133, 134, 135, 138, 140, 141, 142, 143, 144, 145,
        146, 147, 149, 150, 152, 153, 154, 155, 156, 157, 158, 159, 160,
        161, 162, 163, 164, 165, 167, 168, 169, 171, 172, 173, 175, 176,
        178, 179, 180, 181, 182, 184, 186, 187, 188, 189, 190, 191, 192,
        196, 197, 198, 199, 200, 201, 202, 203, 204, 206, 207, 208, 210,
        211, 212, 213, 214, 216, 217, 219, 220, 221

In [23]:
titanic_train.iloc[cabinNA][['Age','Name']]

Age                                      Name
0    22.0                   Braund, Mr. Owen Harris
2    26.0                    Heikkinen, Miss. Laina
4    35.0                  Allen, Mr. William Henry
5     NaN                          Moran, Mr. James
7     2.0            Palsson, Master. Gosta Leonard
..    ...                                       ...
884  25.0                    Sutehall, Mr. Henry Jr
885  39.0      Rice, Mrs. William (Margaret Norton)
886  27.0                     Montvila, Rev. Juozas
888   NaN  Johnston, Miss. Catherine Helen "Carrie"
890  32.0                       Dooley, Mr. Patrick

[687 rows x 2 columns]

In [24]:
titanic_train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [27]:
survivedMale = np.where((titanic_train['Survived'] == 1) & (titanic_train['Sex'] == 'male'))

In [28]:
titanic_train.iloc[survivedMale][['Name','Sex','Survived']]

Name   Sex  Survived
17      Williams, Mr. Charles Eugene  male         1
21             Beesley, Mr. Lawrence  male         1
23      Sloper, Mr. William Thompson  male         1
36                  Mamee, Mr. Hanna  male         1
55                 Woolner, Mr. Hugh  male         1
..                               ...   ...       ...
838                  Chip, Mr. Chang  male         1
839             Marechal, Mr. Pierre  male         1
857           Daly, Mr. Peter Denis   male         1
869  Johnson, Master. Harold Theodor  male         1
889            Behr, Mr. Karl Howell  male         1

[109 rows x 3 columns]

In [29]:
np.random.seed(23)
df = pd.DataFrame(np.random.randn(4,5),index=['a','b','c','d'],columns=['x','y','z','u','v'])

In [30]:
df

x         y         z         u         v
a  0.666988  0.025813 -0.777619  0.948634  0.701672
b -1.051082 -0.367548 -1.137460 -1.322148  1.772258
c -0.347459  0.670140  0.322272  0.060343 -1.043450
d -1.009942  0.441736  1.128877 -1.838068 -0.938769

In [39]:
df.values[df.values<0]

array([-0.77761941, -1.05108156, -0.36754812, -1.13745969, -1.32214752,
       -0.34745899, -1.04345   , -1.00994188, -1.83806777, -0.93876863])

AttributeError: 'numpy.ndarray' object has no attribute 'index'